### ISSUE TITLE
Depot architecture refactor

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#1933]
The Depot our oldest hosted service and needs both a persistence refresh and a proper solution for scalability. Currently the depot is mounted in the Builder-API and the metadata it records about packages is backed by a single Redis instance while the packages themselves are stored on the local file system. We're able to get away with this in the public instance through the use of our CDN, but we need to make changes for the future and to make way for Private Builder.

To do this, we'll make the following changes:
- [x] Depot will no longer be mounted in Builder-API. Instead, it will be it's own service and proxied by the builder-api-proxy (which we may want to rename to http-gateway-proxy) which is just an NGINX service
- [x] Metadata regarding packages will no longer be stored in a Redis instance that the Depot connects to. The metadata will now be stored in OriginSrv (previously known as Vault) and the OriginSrv will delegate messages to a to-be-created full text search service and SchedulerSrv which will build and manage the global metadata index
- [x] Files will no longer be stored on the local file system of the Depot. We will instead write these to an S3 store or another cloud based filesystem. We should think of [minio](https://minio.io) in the private installation of Builder

Here is a diagram of the proposed architecture:
![img_2669](https://cloud.githubusercontent.com/assets/54036/23771407/a341c6f0-04cb-11e7-9d5f-91ede8a4fe8b.JPG)

**Comment by reset** [comment]
Related: #2042

**Comment by mwrock** [comment]
I'm going to close this and move it off of our board. 2 of the 3 items in this epic have been completed: redis-postgres and mobing the depot out of builder-api. The final item re moving to S3 already has its own issue #2697
