### ISSUE TITLE
[web ui] Add "About Us" Page

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2405]
Add "About Us" page and link in footer (for both website and web app):

### Mockup
https://chef.invisionapp.com/share/EU9BOXKF6#/screens/231393034_Habitat_Web_-_About_Us

### To-do
- [ ] Add About Us page on website
- [ ] Add to footer link on website
- [ ] Add to footer link on web app (to About Us on website)

**Comment by apriofrost** [comment]
All core member profile pictures can be found here: https://drive.google.com/open?id=0B6wx-y4RiRvoX2NRUjJ6R25yWEk
The name can be found here: https://docs.google.com/spreadsheets/d/1mmBjtm638YWnPJuzcoRRua8Jz2-Ti303u79qzlVsz4k/edit#gid=0t 
@tashimi do we need to add the titles there? such as what's shown in the mockup^^ we may add the title info to the google sheet agove if we need to.

**Comment by ShalokShalom** [comment]
I suggest replacing the "Depot" or "Explore" section with this one once it gets accepted since they offer the same functionality. In general, I find the term "packages" much more precise in their case.

**Comment by apriofrost** [comment]
Hi @ShalokShalom ! We heard your feedback! We are going to remove the 'Depot' section as you suggested. You can track the issue here: https://github.com/habitat-sh/habitat/issues/2590

Thanks so much for helping us making the site better 👍
