### ISSUE TITLE
Build Service CLI commands

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#2686]
As discussed last week during the office site meetings, @chefsalim expressed the need to improve the experience of working with build service jobs. An outcome of that initial discussion was that he and I review the current workflow and determine what types of tools/solutions could improve that experience and, later, how this could feed into what things we'd need on the web UI side.

Following is a list of potential commands we discussed around working with the build service:

```
hab job start <origin/package> <user defined name for job?>
hab job list
hab job status <id or name>
hab job log <id or name>
hab job retry <id or name>
hab job cancel <id or name>
hab job graph <id or name>
hab job promote <id or name> -channelname
```

The general objective is to only add things as we need them and use a learning-based approach to determine how/where we to grow from this core CLI experience. For example, usage of an initial set of commands could indicate where pain still resides and those commands which would be most beneficial in a GUI format for a wider set of users, potentially.

Clearly needs some further discussion :)

Checklist:

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] hab job start (v1 does not specify branch or tag, see comment below)

- [x] hab job start <origin/package> <user defined name for job?>

- [ ] hab job list

- [x] hab job status <id or name>

- [ ] hab job log <id or name>

- [ ] hab job retry <id or name>

- [ ] hab job cancel <id or name>

- [ ] hab job graph <id or name>

- [x] hab job promote <id or name> -channelname
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by chefsalim** [comment]
One thing we still need to hash out is how to show the job groupings (eg, all the jobs that get kicked off as part of a reverse dependency build group). We could show / manipulate the group behavior from within the 'hab job' commands, or have a separate 'hab job-group' command set.  It probably is simpler to just do the former.

So here's what the commands could do if we went with the consolidated command set.

hab job list - By default, output the list of 'In progress' (ie, building) jobs, and show which group the job belongs to.  Allow parameters to filter the jobs by other states (eg, Not Started, Complete, Failed, etc).  Also have a parameter to show the list of groups instead of the list of jobs.

hab job status - Get the status for a job or a job group.  If showing status for a job group, it will show the status for all the jobs under that group.

hab job cancel - Allow cancelling of either an individual job or a group of jobs, depending on the id specified.  If a specific job is being cancelled, allow the option of cancelling the entire group. Ask for confirmation before issuing a cancel.

hab job retry - Allow retry of a specific job. If job is retried, it will also retry any 'Skipped' jobs that are downstream to the specified job.

hab job promote - Allow promotion of a group of jobs. (It doesn't make sense to promote only a single job).

**Comment by ryankeairns** [comment]
Regarding `hab job graph <id or name>` perhaps it could use something like graphviz to spit out an image of the tree for that job... this may not be in the initial set, but something to consider.

**Comment by chefsalim** [comment]
Yes, that would be an option to consider for hab job graph. Probably the simplest thing would be to show the entire graph, or we could also look at showing the graph rooted at the job specified.

Also I missed a couple of commands, so adding those:

hab job start - Would be used to schedule a group of jobs or a single job (depending on parameter). If scheduling a group of jobs, it would show the complete list of downstream jobs that would be generated, and ask for confirmation before it scheduled the group.

hab job log - Would show the build log of an in-progress, completed, or failed job (if log exists).  Potentially, also be able to show a log of the progression of a group of jobs (may not be in the initial set).

**Comment by raskchanky** [comment]
Per a conversation with @chefsalim yesterday, we're going to postpone allowing `hab job start` to specify a branch or tag to build off until after neighborhoods.

**Comment by mwrock** [comment]
I'm closing this since several of these commands have since been implemented. We can reopen new issues to address any new commands we desire.
