### ISSUE TITLE
Running a Service Group in Kubernetes

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat#2804]
This issue is for tracking the high level progress on running a Service Group in Kubernetes with a [habitat operator](https://github.com/kinvolk/habitat-operator).

The first issue we identified is that in a Kubernetes deployment, all pods need to be started with the same flags, whereas in habitat, users need to pass the `--peer` flag for all but the first service in a service group. This is being addressed as part of #2735.

### habitat part

- [x] Add `--peer-watch-file` flag to supervisor #2735
- [x] Decide on an approach for configuration updates #2805
- [x] Implement `user.toml` watching (#3898)

### Kubernetes operator part

- [x] Implement CRUD operations for Service Group CRD
- [x] [Create ConfigMap with peer pod IP](https://github.com/kinvolk/habitat-operator/issues/11) 

/cc @LiliC @krnowak @tashimi @fnichol

**Comment by rsertelon** [comment]
@asymmetric what is the status on this one? I think there has been an announcement telling that the kubernetes operator was finished, am I right?

**Comment by asymmetric** [comment]
@rsertelon I've updated the issue's checklist.

We can deploy Services to Kubernetes, but [`user.toml` watching](#3898) hasn't been merged yet. I'm currently focusing on something with higher priority, but addressing comments on that PR is next on my list.

The operator itself doesn't need changes to support `user.toml` watching, so in this regard yes, it's "finished".

**Comment by asymmetric** [comment]
All done.
