### ISSUE TITLE
Docker Hub Publish

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2895]
- [x] Refactor `builder.toml` configuration to support configuring post-build publish phases. First candidate should be Docker hub [#2903](https://github.com/habitat-sh/habitat/issues/2903)
- [x] Encrypt sensitive fields (Docker credentials) in configuration [#2896](https://github.com/habitat-sh/habitat/issues/2896)
- [x] Implement publishing to Docker Hub in builder-worker [#3342]
- [x] Visualize publish phases in UI [#2898](https://github.com/habitat-sh/habitat/issues/2898)

**Comment by fnichol** [comment]
#3450 will close out the remaining item once merged.

**Comment by fnichol** [comment]
Sick a fork in this, it's done!
