### ISSUE TITLE
Project Documentation Overhall

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#3127]
This epic is for tracking any issues regarding the habitat open source project documentation including user documentation, user guides, and project docs/wikis a la Contributing.md/Readme.md etc.

- Getting Started Guide
- [x] https://github.com/habitat-sh/habitat/issues/2879
- Local Development Guide
- [ ] https://github.com/habitat-sh/habitat/issues/2882
- Advanced Scaffolding Documentation
- [x] https://github.com/habitat-sh/habitat/issues/2880
- Lifecycle Hooks Documentation
- [x] https://github.com/habitat-sh/habitat/issues/2881
- Contributing Blog Wiki Docs
- [x] https://github.com/habitat-sh/habitat/issues/3128
- Document all sys.* keys 
- [x] https://github.com/habitat-sh/habitat/issues/3129
- Document which scaffoldings can be passed to hab plan init -s
- [x]  https://github.com/habitat-sh/habitat/issues/3095 
- Can't find docs for package promotion
- [x] https://github.com/habitat-sh/habitat/issues/3010
- Building.md Updates
- [ ] https://github.com/habitat-sh/habitat/issues/3006
- Document Composite Plans 
- [ ] https://github.com/habitat-sh/habitat/issues/2902
- Tutorial: config overrides not working in studio
- [ ] https://github.com/habitat-sh/habitat/issues/2767
- Add `export tar` to export docs page
- [x] https://github.com/habitat-sh/habitat/issues/2719
- [Documentation] Document `sup-run` studio functionality
- [x] https://github.com/habitat-sh/habitat/issues/2645
- Project Documentation Overhaul
- [ ] https://github.com/habitat-sh/habitat/issues/3011
- Docs Page UI Tweaks
- [ ] No issue currently assigned. Will draft one.
- Add an article about binlink
- [ ] We currently talk about binlinking all the time, but have no docs explaining what it is and how to use it.
- Update CLI docs 
- [x] https://github.com/habitat-sh/habitat/pull/3162
- Update runtime settings documentation with examples
- [x] https://github.com/habitat-sh/habitat/issues/3167
- Display hooks in execution order and then enhance descriptions
- [x]  https://github.com/habitat-sh/habitat/issues/3166
- Add more troubleshooting documentation
- [ ] https://github.com/habitat-sh/habitat/issues/3165

**Comment by eeyun** [comment]
Lets track progress on our documentation overhaul here.

**Comment by tashimi** [comment]
See #3181, #3180, #3162, #3164, #3151, #3152, #3153
