### ISSUE TITLE
[Builder UI] Add user profile and email

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3351]
As a marketing team member
I would like to help users get started using Habitat
so that they can receive immediate value from the product.

-------------------------

For v1, we would like to capture an email address if one is not sent via GitHub.

When users sign in to the Builder web app, we would also like to convert them to Intercom users in order to follow-up with useful content in getting them off the ground with Habitat.

To do that, we send an identity call as described here:
https://segment.com/docs/destinations/intercom/#identify 

As a pre-req, Intercom will be enabled (snippet added) via the existing Segment integration.
Contact Ryan Keairns and Jason McDonald with questions.

--------------------------

### To-dos

- [x] UX: create mockup for v1 (capture a valid email address)
- [x] Dev: Add dismissible global banner (displays if no email address present and until banner is dismissed or email has been added)
- [x] Dev: Add profile page with email input (including validation)
- [x] Dev: Send email addresses to Intercom

### Mockup
[Mockup of banner, profile, input validation](https://chef.invisionapp.com/share/5WDZ2WORA#/258577709_profile_Email_Empty)

Steps to view all states of prototypes:
- click on email input
- save change
- click on email input to edit; see error
- click on email input to correct
- save change
- note: the banner appears until the email is initially saved/added (it could also be dismissed without adding an email address, but that is not depicted here)

**Comment by ryankeairns** [comment]
In the meantime, Marketing (Matt) would like us to send email lists on Tuesday/Wednesday of each week beginning 10/17.
