### ISSUE TITLE
Add UI instructions for Habitat Builder GitHub App

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3563]
Now that we're using the Habitat Builder GitHub App, users will need to install it before they see any organizations in Step 1 of connecting a plan.

### To-do's

- [x] Change heading on first column / list of orgs
- [x] Add empty state message when no installs are found (i.e. no orgs listed)
- [x] Add sidebar content so that the link to install the Habitat Builder GitHub app is always present

### Mockups
[Empty state mockup](https://chef.invisionapp.com/share/S6DTQIA2Z#/256964791_my_Origin_New_-_Settings_Step_1_Empty_State)
[Has installs mockup](https://chef.invisionapp.com/share/56DT14XRN#/250455391_my_Origin_New_-_Settings_Step_1)
