### ISSUE TITLE
[builder ui] Emphasize GitHub App installation

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3664]
In order to connect a plan to the Build Service, you must first install the Habitat Builder GitHub App. Missing this step will result in error messages and likely confusion, so we'd like to better emphasize this required step in the on-screen instructions.

### To-dos

- [x] Update instructions copy and add button on first step of connecting a plan (mockups below)
- [x] Update the validation messages for both confirmed and errored states (below the text input)
- [x] Add a sidebar with additional help text

### Mockups
[Mockup of repo found](https://chef.invisionapp.com/share/27DQCRSFX#/249855432_create_Package)
[Mockup for invalid repo](https://chef.invisionapp.com/share/ATDV3G25G#/257397776_create_Package_Error)
