### ISSUE TITLE
[builder ui] Edit integrations - docker hub credentials

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3672]
As a user, I want to edit my existing integrations/docker hub creds
so that I don't have to delete and re-add the integration
potentially interfering with packages that have publishing enabled.

### To-dos

- [ ] Add settings icon to the Docker row on the origin > integrations tab
- [ ]  Click icon opens dialog with existing creds (password hidden)
- [ ] Update existing creds and save

### Prototype/Mockups
[Prototype for updating docker hub creds](https://chef.invisionapp.com/share/5YDV6902R#/251489938_my_Origins_Integrations)

**Comment by cnunciato** [comment]
This'll require an API update to return the connection username. (Password should not be returned.)
