### ISSUE TITLE
[builder ui] Bubble up build failure messages in the UI

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3735]
Relates to #3678 

From the conversation in issue #3678 , we're splitting out the concept of bubbling up errors to this new issue.

------------

As a user, I want to quickly know why my build failed
so that I can correct the issue 
and get to a successful build outcome.

If your build fails (regardless of the trigger), let's pipe the failure reason back into the UI on the build output page. So, not only display it in the streaming build output, but above the output box as a separate HTML element/banner/message.

Specific examples would be things like:
- Incorrect Dockhub username or password
- Origin keys not found
- Origin in plan file does not match this origin

### To-dos

- [ ] UX: create mockup of build job error message in UI
- [ ] Dev: Report errors to the frontend end via API
- [ ] Dev: Add message to UI per mockup

**Comment by apriofrost** [comment]
This idea is so brilliant! 
If we have docs that we can link to in the UI to explain possible ways to resolve the error, that will be great!

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #57](https://github.com/habitat-sh/builder/issues/57) via [**ZenHub**](https://www.zenhub.com/)
