### ISSUE TITLE
Add publishing support for the "big 3" container registries

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#3742]
Now that we've got the Docker exporter tied into Builder and publishing to the Docker Hub working it's time to add the other major container registries. This should largely be UI focused with the remainder of the work being in validating credentials which may need to be done server side depending upon each provider's CORS support.

- [x] Amazon Container Registry - #3743
- [ ] Google Container Registry - #3745
- [ ] Azure Container Registry - #3744 

### To-Do's
- [x] UX: Mockups/Prototype for *Integrations* tab w/multiple registry accounts
- [x] UX: Mockups/Prototype for *Connect a plan file* enable publishing w/multiple registries
- [ ] Define form fields (repo and tag format) for each account type (Docker, GCP, Azure, Amazon) 
- [x] UI: Add new buttons to Integrations tab
- [ ] UI: Update help text below label/heading and on delete confirm dialog
- [ ] UI: Display list of accounts on 'Connect a plan file' step 2 when publishing is turned 'ON'
- [ ] UI: Clicking 'configure this account' opens dialog with form (publish settings)
- [ ] UI: After configured, the 'stop sync' icon would disabled publishing for that account (i.e. remove settings; back to original state of 'configure this account')
- [ ] UI: After configured, the 'gear' icon would re-open the dialog with form pre-filled so user can edit settings.
- [ ] UI: Switching publishing to OFF hides the list of accounts and disabled all publishing
- [ ] Credentials verification

### UI Mockups
1. [Prototype for Integrations tab w/multiple registry accounts](https://chef.invisionapp.com/share/5YDV6902R#/251489938_my_Origins_Integrations)
2. [Prototype - publish to multiple registries](https://chef.invisionapp.com/share/M3E0268WQ#/258859130_package_Detail_V2_-_Settings_Connect_Step_2_Multi_Registries)

**Comment by ryankeairns** [comment]
@reset would users need the ability to export and publish to multiple of these per package? 
In other words, when I connect a plan file to builder, could I enable Docker and Amazon, for example?

cc: @elliott-davis

**Comment by elliott-davis** [comment]
Also, do I have the ability to support multiple regions of each of these registries?

cc: @ryankeairns

**Comment by tashimi** [comment]
Yes to both

**Comment by fnichol** [comment]
Beat me to it: yes to both 😄 

We designed the "integrations" to be a list so that there could be multiple types (docker hub, ami), and multiple instances of the same type (ami/us-west-2, ami/us-east-1, etc)

**Comment by ryankeairns** [comment]
![tenor-47856026](https://user-images.githubusercontent.com/446285/31632564-07b84f0e-b283-11e7-8f4b-9c2e2dffee45.gif)

**Comment by ryankeairns** [comment]
Prototype link added to issue description for the Integrations tab. Next, working on prototype for the multiple registry targets in the 'connect a plan file' flow.

**Comment by ryankeairns** [comment]
What do you all think of this approach for publishing to multiple registries? Re-using existing design patterns elsewhere in the app (the table list and modal dialogs).

In this mini prototype, you can add Docker Hub publishing, then remove it.
[Prototype - publish to multiple registries](https://chef.invisionapp.com/share/M3E0268WQ#/258859130_package_Detail_V2_-_Settings_Connect_Step_2_Multi_Registries)

**Comment by reset** [comment]
@ryankeairns I think it looks great - I think it's just fine for now to publish to only one of each type but I think in the future people may want to be able to publish to `n` number of Docker Hub repositories

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #58](https://github.com/habitat-sh/builder/issues/58) via [**ZenHub**](https://www.zenhub.com/)
