### ISSUE TITLE
[www][Builder UI] Download links should be easier to find on website

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3819]
Currently, our downloads page is buried down in our Tutorials section, or linked to from an easy-to-overlook link in the page footer.

It would be nice for there to be a more prominent and obvious link to the download instructions.

### To-do
- [ ] Add download link (button) on docs home page (see mockup)
- [ ] Add download link (button) at bottom of docs left-hand navigation
- [ ] Add download link to the Quick Links section of the left-hand navigation in the Builder Web App UI

**Note**
All three links point to https://www.habitat.sh/docs/using-habitat/#install-habitat

### Mockups
1. Docs home and left nav mockup: https://chef.invisionapp.com/share/72E4BZA6P#/screens/260160886
2. Builder UI Quick Links mockup: https://chef.invisionapp.com/share/72E4BZA6P#/screens/260124724

**Comment by mwrock** [comment]
YES! Would be great to get the link back to a prominant spot on the home page.

**Comment by burtlo** [comment]
This feels particularly important with the current steady stream of releases. I would second that and add that I would enjoy seeing a version number.

I wouldn't mind if we had https://downloads.habitat.sh had the release notes as well that get posted to the forum. Or perhaps what I would like to help with is getting those release notes back over on the GitHub release page (https://github.com/habitat-sh/habitat/releases)

**Comment by mgamini** [comment]
Thoughts @ryankeairns ?

**Comment by ryankeairns** [comment]
There is a related issue here - https://github.com/habitat-sh/habitat/issues/3684 
Liz notes creating some mockups in that issue... @apriofrost can you mock up where the Download Link should appear in the website and web app IA/navigation?  Thank you!

**Comment by eeyun** [comment]
Some of this work was started with the docs refactor. It was actually the impetus for abstracting a bunch of content out into partials. The downloads page content that's used in the tutorial is already a partial and the styling should be accessible anywhere on the site, it also shows up in the docs pages. Which means, we might be able to literally create a new blank page with the core styling add a simple sidebar that reflects the download options, and be g2g with very little effort. 

WRT getting changelog exposed to the downloads page I think the simplest option would be to have a button that links to the forum where we post our release notes in case users want to read them, without obligating them to look through N+1 lines of release notes to grab the package download? Not sure if that would be bad UX though.

**Comment by apriofrost** [comment]
@ryankeairns Sure! Working on the mockup, will post it here later today or early tomorrow. Thanks!

**Comment by apriofrost** [comment]
Two proposed changes to surface the download link more:
1. Add the `Download CLI` link under the Quick Links in the Builder left nav. When clicking/taping on it, it opens the [related doc page](https://www.habitat.sh/docs/using-habitat/#install-habitat) in a new tab/window.
See mockup: https://chef.invisionapp.com/share/72E4BZA6P#/screens/260124724
2. Add the `Download Habitat CLI` button on the [docs home page](https://www.habitat.sh/docs/). When clicking/taping on it, it opens the [related doc page](https://www.habitat.sh/docs/using-habitat/#install-habitat) in the current tab/window.
See mockup: https://chef.invisionapp.com/share/72E4BZA6P#/screens/260160886

Feel free to add your comments in the mockup by turning on the comment feature at the bottom right corner of the mockup window.

Thank you!

**Comment by apriofrost** [comment]
Hi @cnunciato there is another half of this fix that's inside the Builder UI. Could you tackle this one?

Builder UI Quick Links mockup: https://chef.invisionapp.com/share/72E4BZA6P#/screens/260124724

**Comment by ryankeairns** [comment]
@apriofrost the work to add a download link to the quick start/Builder UI side navigation was part of that PR, it just hasn't been pushed to acceptance or production yet.
