### ISSUE TITLE
API re-vamp

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#4013]
The purpose of this issue is to track the progress towards making our public HTTP API more robust and easier to maintain. To that end, there are several things we're investigating.

- [ ] Rewriting our API docs with https://swagger.io. The API docs we have are patchy at best and could stand to be substantially improved.
- [x] Finishing the integration test suite that we currently have so that it covers the entire Builder API
- [ ] With a solid set of tests in place, we can begin to write v2 of our HTTP API using a modern and maintained Rust web library that's more developer-friendly, such as http://rocket.rs. This will also be a great chance to re-visit the URL structure for our API and make any changes necessary to ensure it makes sense for consumers.

**Comment by raskchanky** [comment]
I've written up 3 gists regarding the new v2 API and its URL structure.

* [Current v1 routes](https://gist.github.com/raskchanky/ce7c54228a733abc19e0ae091ea5802c)
* [Proposed v2 routes](https://gist.github.com/raskchanky/e925bb8b6b29ddd1b6b2711cece977f1)
* [Rationale behind the changes](https://gist.github.com/raskchanky/8ce45c7e63fd25d7b7c868bcbf0fb5f0)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #71](https://github.com/habitat-sh/builder/issues/71) via [**ZenHub**](https://www.zenhub.com/)
