### ISSUE TITLE
Provide more visual distinction between public and private keys

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4054]
Currently, private and public keys are only visually distinguished by a subtle slash through the "eye" icon. It would be nice to provide more visual distinction (e.g., putting private keys behind a "show private keys" button, put them under a big "🚧 WARNING 🚧" banner, etc.)

-----------

### To-do
- [x] Add 'private' tag/label to private key row
- [x] Align both upload buttons to the ride side of the tables
- [x] Remove the eye icon from the public key rows
- [x] Remove the `<hr>` between the private and public sections
- [x] Set the spacing between the private and public sections 60px

### Mockup
https://chef.invisionapp.com/share/TSEGSW52H#/250295491_origin_Keys_Download

**Comment by ryankeairns** [comment]
@christophermaier How does this feel? I've tweaked a few things to provide more visual clarity:

- added a 'private' tag 
- removed the eye icon on the public keys so that the eye with line has more prominence
- moved the upload buttons to the right, making it easier to scan the keys and to make the table headers/titles more obvious

https://chef.invisionapp.com/share/TSEGSW52H#/250295491_origin_Keys_Download

**Comment by christophermaier** [comment]
@ryankeairns Big improvement!

![tenor-24988307](https://user-images.githubusercontent.com/207178/32807714-cbd82a52-c95e-11e7-886a-529246246761.gif)

**Comment by ryankeairns** [comment]
@cnunciato this is a smaller one that I wanted to bring to your attention.
