### ISSUE TITLE
Replace the Habitat logo

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#4846]
This purpose of this issue is to give us an initial list to work by as we replace the Habitat logo. (We may not need to replace every occurrence;  just figured it'd be good to capture as much as possible up front, then make decisions as we go.) 

* [x] [Builder sign-in](https://bldr.habitat.sh/#/sign-in)
* [x] [Builder main nav](https://bldr.habitat.sh/#/pkgs/core)
* [x] Builder favicon
* [x] [Website main nav](https://www.habitat.sh/)
* [x] [Website footer](https://www.habitat.sh/#main-footer) (logo, app stack, cat pants)
* [x] Website favicon
* [x] [Pricing page](https://www.habitat.sh/pricing/)
* [x] [Packaging demo](https://www.habitat.sh/demo/packaging-system/steps/2/)
* [x] [GitHub org](https://github.com/habitat-sh)
* [x] [Twitter](https://twitter.com/habitatsh)
* [x] [YouTube Channel](https://www.youtube.com/channel/UC0wJZeP2dfPZaDUPgvpVpSg?view_as=subscriber)
* [x] [StatusPage](https://status.habitat.sh/)
* [x] [Forums nav](https://forums.habitat.sh/)
* [x] [Habitat Slack team avatar](https://habitat-sh.slack.com/home)
* [x] [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=cnunciato.habitat) (cnunciato's)
* [x] [VSTS integration](https://marketplace.visualstudio.com/items?itemName=chef-software.vsts-habitat-tasks) (owned by internal chef partner team)
* [x] [Infographics](https://www.habitat.sh/docs/reference/#infographics)
* [x] [Sample Node app](https://github.com/habitat-sh/sample-node-app)
* [x] [Build and sign icons](https://www.habitat.sh/learn/)
* [x] [GitHub apps](https://github.com/organizations/habitat-sh/settings/apps)
* [x] [Embedded screenshots](https://www.habitat.sh/demo/build-system/steps/3/) (several)
* [x] [Tip icon](https://www.habitat.sh/demo/process-supervisor/steps/1/)
* [x] [Node guide screenshot](https://www.habitat.sh/tutorials/build-your-own/node/define-dependencies/)
* [x] [These, too, maybe](https://www.habitat.sh/blog/2017/10/node-with-db/)
* [x] [Habicaps](https://www.habitat.sh/blog/2017/10/distributed-java-application/)
* [x] [The GIF in this blog post](https://www.habitat.sh/blog/2017/10/habitatize-ruby-web-application/)
* [x] [Launch banner](https://www.habitat.sh/blog/2017/10/Habitat-Builder-for-the-People/)
* [x] [Birthday balloon](https://www.habitat.sh/blog/2017/06/Happy-Birthday-Habitat/)
* [x] Home-page video intro and outro cards
  
## learn.chef.io

* [x] [Try Habitat page](https://learn.chef.io/modules/try-habitat#/) ([PR here](https://github.com/chef/chef-web-learn/pull/1355))
* [x] [Build page](https://learn.chef.io/modules/hab-web-app-builder#/)
* [x] [Reconfigure page](https://learn.chef.io/modules/hab-custom-config#/)

Pull requests can be issued on [the LearnChef repo](https://github.com/chef/chef-web-learn).

## chef.io

* [x] [Home page](https://www.chef.io/)
* [x] [**Products** item in the main nav](https://www.chef.io/)
* [x] [Application Automation page](https://www.chef.io/solutions/application-automation/)

## chefconf.chef.io

* [x] [Home page](http://chefconf.chef.io/)

## brand.chef.io

* [x] Take it down, redirect to www

## stackshare.io
* [x] [Profile picture](https://stackshare.io/habitat)

**Comment by apriofrost** [comment]
The list is so great! A couple of comments:
1. the Habicatps - Microsoft creates this graphic, and I don't have the source file. I think we can ignore this one for now.
2. The Chef branding site - the rules set up by the site hasn't persisted since Andy, the designer who created this site left Chef. One evidence is the horizontal Chef logo is showing up anywhere on Chef web properties. I think we need to have a discussion with marketing folks about this, whether we should keep maintaining this site or not.
3. I would suggest us add a folder in the GitHub repo specifically for the logos so that media and community members can use at their convenience. The folder will include all the logo variations for download and a README for usage and terms and conditions.

**Comment by cnunciato** [comment]
@apriofrost Excellent, all that sounds great. I'll add an item to capture the logo folder and README -- that's a great idea. ❤️

**Comment by apriofrost** [comment]
When we are doing point 3 above, we will also make the logo height/width consistent according to @rsertelon 's suggestion.

**Comment by cnunciato** [comment]
Let's use this issue as an Epic and create individual issues and PRs that refer to it, so we're clear on who's doing what and don't do any duplicate or conflicting work.

**Comment by cnunciato** [comment]
Closing as complete.
