### ISSUE TITLE
Update to Rust 1.27.1

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#5357]
Merging the following to update Habitat to Rust 1.27.1!

- [x] Merge habitat-sh/core-plans#1708
- [x] Merge habitat-sh/core#43
- [x] Merge habitat-sh/habitat#5356
- [x] Merge habitat-sh/builder#540

For the curious, here's the process from [Upgrading Habitat to a New Rust Release](https://forums.habitat.sh/t/upgrading-habitat-to-a-new-rust-release/693)

![tenor-8077950](https://user-images.githubusercontent.com/261548/42904296-caa73eda-8a91-11e8-8ee1-13e11607b968.gif)

**Comment by fnichol** [comment]
All done!
