### ISSUE TITLE
Update to Rust 1.28.0

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#5413]
Merging the following to update Habitat to Rust 1.28.0!

- [x] Merge habitat-sh/core-plans#1760
- [x] Merge habitat-sh/core#50
- [x] Merge habitat-sh/habitat#5412
- [x] Merge habitat-sh/builder#569

For the curious, here's the process from [Upgrading Habitat to a New Rust Release](https://forums.habitat.sh/t/upgrading-habitat-to-a-new-rust-release/693)

![tenor-8077950](https://user-images.githubusercontent.com/261548/42904296-caa73eda-8a91-11e8-8ee1-13e11607b968.gif)
