### ISSUE TITLE
Update to Rust 1.29.1

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#5736]
Merging the following to update Habitat to Rust 1.29.1!

- [x] Merge habitat-sh/core-plans#1903
- [x] Merge habitat-sh/core#74
- [x] Merge habitat-sh/habitat#5735
- [x] Merge habitat-sh/builder#721

For the curious, here's the process from [Upgrading Habitat to a New Rust Release](https://forums.habitat.sh/t/upgrading-habitat-to-a-new-rust-release/693)

![tenor-8077950](https://user-images.githubusercontent.com/261548/42904296-caa73eda-8a91-11e8-8ee1-13e11607b968.gif)

https://blog.rust-lang.org/2018/09/25/Rust-1.29.1.html
