### ISSUE TITLE
Remove Eventsrv interface

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6012]
## Description
Eventsrv is essentially a prototype that hasn't been used in some time. We should start by removing this interface to reduce our support area.

## Acceptance Criteria
- [ ] Eventsrv interface is removed, but the source code still remains
- [ ] Documentation related to Eventsrv hook is removed
- [ ] If the CLI interface needs to be changed ensure that the breaking change is communicated clearly in our release notes. Give @dmccown a heads-up as well.
