### ISSUE TITLE
Release 0.74.0 checklist

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#6090]
Here are all the steps for the release process. Create a new issue at the beginning and check them off as you go. This issue exists to track progress on the release and ensure all the steps are carried out. When you're done just close the issue.

## Release 0.74.0 specific activities

- [x] Merge habitat-sh/core#114 to address macOS build
- [x] Merge habitat-sh/habitat#6108 to bump `habitat-sh/core` dependency
- [x] Merge habitat-sh/habitat#6103 to upgrade to Rust 1.32.0
- [x] Merge habitat-sh/habitat#6112 rebased against master to account for CHANGELOG updates and as a version release commit (despite version number not moving)
- [x] Change date on install hook blog post and link from release notes
- [x] Write up or link to behavior change backround relating to habitat-sh/habitat#6087 in release notes
- [x] Build, upload, and promote `x86_64-windows` Rust 1.32.0 package
- [x] Promote Linux Rust 1.32.0 package
- [x] Build, upload, and promote `x86_64-linux-kernel2` Rust 1.32.0 package

## Release activities

- [x] [Check if release will cause downtime and if so appropriately announce it](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#if-your-release-is-going-to-cause-downtime)
- [x] Release new launcher or confirm there have been no launcher changes since the [last stable version](https://bldr.habitat.sh/#/pkgs/core/hab-launcher/latest)
- [x] Declare merge freeze and update slack status
- [x] [Create PR](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#prepare-master-branch-for-release) to update [`VERSION`](https://github.com/habitat-sh/habitat/blob/master/VERSION)
- [x] Fix up any miscategorization in [CHANGELOG.md](https://github.com/habitat-sh/habitat/blob/master/CHANGELOG.md) and add to PR updating [`VERSION`](https://github.com/habitat-sh/habitat/blob/master/VERSION)
- [x] [Merge PR](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#prepare-master-branch-for-release) to update [`VERSION`](https://github.com/habitat-sh/habitat/blob/master/VERSION)
- [x] [Create blog announcement PR](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#submit-a-release-notes-blog-post-pr) and solicit team member input
- [x] [Buildkite](https://buildkite.com/chef/habitat-sh-habitat-master-release) run success
- [x] [Build Windows Docker Studio](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#build-the-windows-docker-studio-image)
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [darwin binaries](https://bintray.com/habitat/stable/hab-x86_64-darwin)
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [linux binaries](https://bintray.com/habitat/stable/hab-x86_64-linux)
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [linux-kernel2 binaries](https://bintray.com/habitat/stable/hab-x86_64-linux-kernel2)
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [windows binaries](https://bintray.com/habitat/stable/hab-x86_64-windows)
- [x] Confirm validation in Buildkite to complete promotion
- [x] Declare merge thaw and update slack status
- [x] Merge blog announcement PR
- [x] [Update builder bootstrap bundle](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-builder-bootstrap-bundle)
- [x] [Update homebrew tap](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-homebrew-tap)
- [x] [Update chocolately package](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#rerun-chocolatey-validation-tests)
- [x] [Publish release](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#publish-release) on GitHub
- [x] [Update `hab-backline` to release version in acceptance environment](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-the-acceptance-environment-with-the-new-hab-backline)
- [x] [Update docs](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-the-docs)
- [x] [Bump version](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#bump-version) to new `-dev` version
- [ ] [Update `hab-backline` to new `-dev` version in acceptance environment](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-the-acceptance-environment-with-the-new-hab-backline-1)
- [ ] [Promote builder worker](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#promote-the-builder-worker) and confrm build uses new version
- [x] Post announcement in [Chef discourse](https://discourse.chef.io/c/habitat)
- [x] Post announcement in [Habitat forums](https://forums.habitat.sh/c/announcements)
- [x] Tweet announcement from `@habitatsh`
- [ ] [Update `Cargo.lock`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-cargolock) for [`core`](https://github.com/habitat-sh/core)
- [ ] [Update `Cargo.lock`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-cargolock) for [`habitat`](https://github.com/habitat-sh/habitat)
- [ ] [Update `Cargo.lock`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-cargolock) for [`builder`](https://github.com/habitat-sh/builder)
- [ ] Review release automation and/or [`RELEASE.md`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md) and add necessary fixes

**Comment by fnichol** [comment]
In running the builds, we discovered that we need to update our macOS version on our worker as we phased out our 10.11 platform very recently. I'll be issuing a PR to bump our Mac builders to macOS 10.12 and we'll restart the build process.

**Comment by mwrock** [comment]
A few items to add form this release's checklist:
- [ ] Edit file name and date of https://github.com/habitat-sh/habitat/blob/master/www/source/blog/2019-03-04-introducing-the-install-hook.html.md
- [ ] Ensure https://github.com/habitat-sh/habitat/pull/6095 is added to fixes in changelog
- [ ] Add words about the movement of the `results` folder (will add them here in a separate comment)

**Comment by fnichol** [comment]
The core-bumping PR habitat-sh/habitat#6108 is working its way through CI and pending review

**Comment by mwrock** [comment]
One change to the Windows build system in 0.74.0 changes the location of the `results` folder where the final `hart` file is saved upon a successful build. Until 0.74.0, the `results` folder would always exist under the folder where the `plan.ps1` file is located. We have changed this location so that the `results` folder is created inside the current working directory. Thus the `results` folder will exist in the same directory from wherever you call `build` if you are inside of a Studio or from where you call `hab pkg build`.

The reason for this change is that this aligns the Powershell build behavior with the Bash based behavior for `plan.sh` based plans. We make an effort to align these behaviors in order to simplify the overall behavior of any Habitat build and align expectations and documentation around the Habitat build system in general. The particular detail of the `results` folder location came to light as we have been working on adding Windows builder workers to our public Habitat CI offering.

If you have built CI infrastructure around Windows based Habitat builds, this change may impact you if you invoke a build from a location above the immediate folder where your `plan.ps1` is located. If you typically run `build` from the same directory where the `plan.ps1` is located, this change should have no affect.

**Comment by fnichol** [comment]
Update from last week: we were ready to resume the Build Kite-driven released pipeline when we hit another underlying infrastructure change from the last release around script execution/upload permissions. We've had to make a couple of changes to the pipeline setup configuration and that work is still ongoing. Once we're able to see the pipeline proceed, then it's back to normal processes.

**Comment by fnichol** [comment]
Release is out!
