### ISSUE TITLE
Clippy tracking issue

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#6213]
Links in **bold** are PRs in review. All tasks are @baumanj unless otherwise noted.

- [X] [Agree on lint standards](https://github.com/habitat-sh/habitat/pull/6100)
- [x] Fix lints that cause errors
  - [X] [habitat](https://github.com/habitat-sh/habitat/pull/6046)
  - [x] core
  - [X] [builder](https://github.com/habitat-sh/builder/pull/846)
- [x] Add clippy checking to CI
  - [x] Share lint definitions across platforms
    - [x] [Linux](https://github.com/habitat-sh/habitat/pull/6325)
    - [x] [Windows](https://github.com/habitat-sh/habitat/pull/6330) (@mwrock)
  - [x] Linux
    - [X] [habitat](https://github.com/habitat-sh/habitat/pull/6046)
    - [x] [core](https://github.com/habitat-sh/core/pull/141)
    - [x] [builder](https://github.com/habitat-sh/builder/pull/977)
  - [x] Windows (@mwrock)
    - [x] [habitat](https://github.com/habitat-sh/habitat/pull/6330)
    - [x] ~~core~~
    - [x] **[builder](https://github.com/habitat-sh/builder/pull/1027)**
- [x] Fix lints that cause warnings and upgrade them to error-causing
  - [x] habitat
    - [X] [clippy::redundant_field_names](https://github.com/habitat-sh/habitat/pull/6210)
    - [X] [clippy::needless_update](https://github.com/habitat-sh/habitat/pull/6210)
    - [X] [clippy::len_without_is_empty](https://github.com/habitat-sh/habitat/pull/6198)
    - [x] [clippy::wrong_self_convention](https://github.com/habitat-sh/habitat/pull/6231)
    - [x] [clippy::trivially_copy_pass_by_ref](https://github.com/habitat-sh/habitat/pull/6232)
    - [x] [clippy::needless_pass_by_value](https://github.com/habitat-sh/habitat/pull/6241)
    - [x] [clippy::clippy::cyclomatic_complexity](https://github.com/habitat-sh/habitat/pull/6321)
    - [x] [clippy::clippy::large_enum_variant](https://github.com/habitat-sh/habitat/pull/6272)
    - [x] [clippy::clippy::needless_return](https://github.com/habitat-sh/habitat/pull/6334/files) (@christophermaier per 
https://github.com/habitat-sh/habitat/pull/6100#discussion_r252432625)
    - [x] [clippy::clippy::too_many_arguments](https://github.com/habitat-sh/habitat/pull/6305)
    - [x] [Changes for clippy lint fixes from core](https://github.com/habitat-sh/habitat/pull/6288)
  - [x] core
    - [X] [Fix clippy lints](https://github.com/habitat-sh/core/pull/135)
    - [X] [Change `PackageTarget::active_target()` to return non-reference](https://github.com/habitat-sh/core/pull/135)
    - [x] [Make `PairType` `Copy`](https://github.com/habitat-sh/core/pull/135) and change references
  - [x] builder
     - [x] [Changes for clippy lint fixes from core](https://github.com/habitat-sh/builder/pull/973)
     - [x] [Fix clippy lints and update CI](https://github.com/habitat-sh/builder/pull/977)

**Comment by mwrock** [comment]
closing this since all boxes are checked

**Comment by raskchanky** [comment]
Part of [merging the core repo back into habitat](https://github.com/habitat-sh/habitat/pull/6432) involved fixing a bunch of clippy lints that hadn't been tackled before, almost all of which were in Windows specific code.

We should go back through and address these clippy lints under a less hectic schedule, and either leave them as is (allowed), or address them properly.  I've marked all of them with a `// TODO` comment to fix, but here are the files that were affected:

https://github.com/habitat-sh/habitat/blob/master/components/win-users/src/sid.rs
https://github.com/habitat-sh/habitat/blob/master/components/core/src/os/process/windows_child.rs
https://github.com/habitat-sh/habitat/blob/master/components/core/src/os/ffi/windows.rs
https://github.com/habitat-sh/habitat/blob/master/components/butterfly-test/src/lib.rs

I'm not going to link to specific line numbers because it's possible that those numbers will change by the time someone looks at this, but searching for `TODO JB` or `allow(clippy` inside each of those files will find the appropriate items.
