### ISSUE TITLE
Eliminate deadlocks due to recursive read locking

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#6435]
Currently, the read/write locks in the supervisor are mostly [`std::sync::RwLock`](http://doc.rust-lang.org/std/sync/struct.RwLock.html), which has no defined semantics in the case a thread calls `read` when the thread already holds a read lock: it may deadlock or panic. The current implementation on Linux seems to support recursive read locks, while the current Windows implementation seems to deadlock. This leads to inconsistent deadlocks in our test code (and presumably in production).

To resolve this problem safely, we will work in phases:
1. Change read/write locks to an implementation which safely supports recursive read locks
1. Replace read/write locks with simple mutexes in test builds to find and eliminate recursive read locks
1. Eliminate recursive locking logic

Step 1 requires an implementation which may starve writers, but that's preferable to deadlocking. After tracking down all the recursive read lock scenarios, we can change to a fair, non-recursive implementation or read/write locks, while continuing to use mutexes in test builds to help catch any regressions that re-introduce recursive locking. This work needs to be done for all `RwLocks`, but we will do it one type at a time in order to learn how the process works and not make too many changes all at once.

- [X] [`MemberList`](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/src/member.rs#L326): https://github.com/habitat-sh/habitat/pull/6436
- [X] [`RumorStore`](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/src/rumor/mod.rs#L127): https://github.com/habitat-sh/habitat/pull/6674
- [x] [`Server`](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/src/server.rs#L232) https://github.com/habitat-sh/habitat/pull/6941
- [x] [`promote::test::OutputBuffer`](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/bldr/job/promote.rs#L186) @raskchanky 
- [x] [`binlink::test::OuptutBuffer`](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/pkg/binlink.rs#L489) @raskchanky
- [x] [`build::test::OutputBuffer`](https://github.com/habitat-sh/habitat/blob/master/components/pkg-export-docker/src/build.rs#L983) @raskchanky
- [x] [`Manager`](https://github.com/habitat-sh/habitat/blob/bf0d0026deb1256cd154178c818fb8a9c6b2f909/components/sup/src/manager.rs#L363) https://github.com/habitat-sh/habitat/pull/6940
- [x] [`ManagerState::services`](https://github.com/habitat-sh/habitat/blob/bf0d0026deb1256cd154178c818fb8a9c6b2f909/components/sup/src/manager.rs#L344) https://github.com/habitat-sh/habitat/pull/6956
- [x] [`RumorHeat`](https://github.com/habitat-sh/habitat/blob/bf0d0026deb1256cd154178c818fb8a9c6b2f909/components/butterfly/src/rumor/heat.rs#L50) https://github.com/habitat-sh/habitat/pull/6957
- [x] All the following instances share a `GatewayState` reference, and should be considered part of the same lock:  https://github.com/habitat-sh/habitat/pull/6937
    - [`http_gateway::AppState`](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/http_gateway.rs#L96)
    - [`ManagerState`](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager.rs#L346)
    - [`service::health::State`](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/service/health.rs#L64)
    - [`Service`](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/service.rs#L159)

Once all the `RwLocks` are converted we can change their `read` and `write` methods to a fair, non-recursive implementation.
