### ISSUE TITLE
Modernize error handling

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6559]
Our error types are getting a bit crufty; we can make them much better!

- [x] https://github.com/habitat-sh/habitat/issues/6555 - remove `description`
- [ ] https://github.com/habitat-sh/habitat/issues/6556 - implement `source`
- [ ] https://github.com/habitat-sh/habitat/issues/6557 - modularize errors
- [ ] https://github.com/habitat-sh/habitat/issues/6558 - use `failure` crate

**Comment by davidMcneil** [comment]
See this [discussion](https://github.com/habitat-sh/habitat/pull/6794#discussion_r311329903) for ideas on error handeling.

**Comment by mwrock** [comment]
still relevant
