### ISSUE TITLE
Logging Overhaul

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6587]
- [x] #6500 - runtime logging configuration
- [x] #6583 - ease transition from `env_logger` to `log4rs`
- [ ] #6584 - consolidate "user-facing" output and logging concerns
- [x] #6585 - decouple logging from Supervisor error implementation
- [ ] #6586 - allow for easier modification of log4rs-based logging
- [ ] #6588 - consider owning our own logging configuration refresh
- [ ] #6625 - investigate the use of `tokio-trace`
- [ ] #6632 - Use log4rs everywhere
