### ISSUE TITLE
Automate Dashboard Follow-Up Work

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6607]
- [ ] #6604 Send health check events on separate NATS subject
- [ ] #6605 Investigate possibility of sending health check events over non-streaming NATS connection
- [ ] #6606 Convert event message structure to an "envelope"-based structure
- [ ] #6706 Create finer-grained events around service updating
