### ISSUE TITLE
[certs] Add cert tests to end-to-end tests

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6800]
Related to https://github.com/habitat-sh/habitat/pull/6759

This is a work item to add cert tests to the hab e2e suite

The following scenarios should be addressed by the test suites:
For scenarios involving the studio,  the following combinations should be considered:
>Linux - chroot studio
Linux - docker studio
Linux-kernel2 - chroot studio 
MacOS - docker studio
Windows - native studio
Windows - Windows docker studio
Windows - Linux docker studio 

- [ ] Clean hab environment can communicate with Builder
  - [ ] Fresh hab install
  - [ ] Check the contents on “/hab/cache/ssl” and “~/.hab/cache/ssl” - it should look sane.
  - [ ] Do a package install - eg, “hab pkg install core/redis”
  - [ ] Ensure that basic communication to Builder continues to function

- [ ] Entering a clean Studio should work 
  - [ ] Able to do basic commands normally, eg, a package build
  - [ ] Can communicate with Builder from within Studio
  - [ ] The contents of “/hab/cache/ssl” should look sane

- [ ] Placing a certificate in the hab ssl cache propagates to the studio (`/hab/cache ssl` or `~/.hab/cache/ssl`)
  - [ ] Certificate named something other than `cert.pem`
  - [ ] Enter the Studio and ensure that the cert is propagated to the “/hab/cache/ssl” folder
  - [ ] Ensure that basic communication to Builder continues to function

- [ ]  Self-signed certs are successfully used to talk to Builder
  - [ ] Short-term: Inspect `RUST_LOG=debug` output showing the certificate was loaded
  - [ ] Long-term: Stand up an on-prem builder with a self signed cert and verify interaction

- [ ] The SSL_CERT_FILE environment variable is respected 
  - [ ] Ensure that hab outside the Studio loads the cert 
  - [ ] Ensure SSL_CERT_FILE is set correctly inside the studio (#6944)
  - [ ] Ensure that the cert is present in the studios `/hab/cache/ssl` directory (#6944)
  - [ ] Ensure that basic communication to Builder succeeds both inside and outside the Studio (#6944)

- [ ] Negative testing
  - [ ] Bad (malformed) self-signed cert file is ignored (#6944)
  - [ ] SSL_CERT_FILE empty or pointing to missing file (#6944)
  - [ ] SSL_CERT_FILE pointing to a non-file (#6944)

**Comment by krasnow** [comment]
Blocked on 0.87 release
