### ISSUE TITLE
Chef Habitat Documentation Refresh

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#6875]
[Draft]
The Chef Habitat documentation is due for an update. Users have complained to us about deficiencies in our documentation, the documentation team has been working on new patterns for writing, building, and maintaining documentation, and the documentation team is also preparing for changes in how we publish Chef documentation in the near future.

The goal of the Chef Habitat documentation refresh is to:

- Create great documentation, in line with our vision for [Docs@Chef](https://docs.google.com/document/d/1M1SpGolgQM6TKPo6DhDQIAPPA6Tlr9WurghTxDtkDTs/edit?usp=sharing)
- Improve the user experience in searching and browsing our technical documentation
- Make Chef Habitat documentation clear, correct, and current
- Implement consistent information design practices
- Build and publish technical documentation with the same tools throughout Chef Software

Known work:
- [ ] Simplify contributing to and maintaining the docs by removing single-use partials
- [ ] Introduce consistent tooling for search by moving to SwiftType
- [ ] Use consistent documentation design
- [ ] Use consistent patterns to generate docs from code for reference materials
- [ ] Use the documentation team/release engineering "seamless release notes" process beginning with the 2.0 release notes

**Comment by mwrock** [comment]
closing since all child issues are closed.
