### ISSUE TITLE
Add windows supervisor specific end-to-end tests

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6965]
Fortunately the vast majority of supervisor behavior is platform agnostic and most of the more nuanced linux tests should satisfy windows scenarios. However we should, at a minimum, add the following tests:

- [x] The supervisor can start and load/run a simple service (#7005)
- [x] The windows service package can install itself and run the supervisor (#7006)
- [x] A package with an alternate `svc_user` can run loaded with a `svc_password` under the `svc_user` credentials (#7008)
- [x] Stopping the supervisor gracefully stops the service and cleans up running `pwsh` processes (#7009)
