### ISSUE TITLE
Use modern tools on the website        

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#7301]
Some of the tools that we use on the website are outdated. We also need to step out of slim for templating in order to make the Hugo conversion smoother.

- [ ] Upgrade Ruby to [current/2.6.5 ](https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/). We are on [2.5.3](https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/)
- [ ] Upgrade Foundation to [current/6.5.3](https://github.com/foundation/foundation-sites/blob/develop/.versions) We are on either [6.2](https://github.com/habitat-sh/habitat/blob/master/www/source/stylesheets/vendor/foundation/foundation.scss) or [6.4.3](https://github.com/habitat-sh/habitat/blob/master/www/source/javascripts/vendor/foundation.min.js)
- [ ] Upgrade JQuery to [3.4.1 or higher](https://blog.jquery.com/2019/05/01/jquery-3-4-1-triggering-focus-events-in-ie-and-finding-root-elements-in-ios-10/). We are on [2.4.1](https://github.com/habitat-sh/habitat/blob/master/www/source/javascripts/vendor/jquery.min.js)
- [ ] Transform SLIM to either HTML or Middleman. HTML should be easier to convert to Hugo, but there could be a Middleman -> Hugo tool by now.
- [ ] Middleman current is 4.3.5. I don't think we are pinned to a version.
- [ ] I'm not sure of the versions or need for most of what is in `www/source/javascripts/vendor/foundation.min.js`

**Comment by krasnow** [comment]
Closing -- Marketing is building us a fancy new Hab site.
