### ISSUE TITLE
Improve API retry logic around package installation, and beyond

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7671]
Recently, a handful of issues relating in one way or another to API retry logic have popped up:

* https://github.com/habitat-sh/habitat/issues/7639
* https://github.com/habitat-sh/habitat/issues/7619
* https://github.com/habitat-sh/habitat/issues/7670

The first two deal with retries that aren't sufficiently smart (e.g., repeatedly making requests that always return 404). That is, retrying API calls should be limited to situations where a retry _of the same request_ is likely to result in a success, as with request timeouts. If you get a `Forbidden` result from an API call, trying the call four more times with the same credentials is unlikely to result in success.

The third issue deals with the fact that while we have retry logic around the API call to fetch packages, we don't have it around other API calls that are also in the package installation flow. It doesn't make sense for only part of the installation flow to be robust against network timeouts, and any retries we add here would also need to be sufficiently "smart" to be truly useful.

This suggests that we might want to add retriability as part of our API client crate itself. This would ensure that the proper logic is added to where it is most directly needed, and would allow callers to easily adopt the desired amount of retries by calling a new function, or perhaps passing an `Option<uint>` argument to existing functions indicating the number of retries.

**Comment by sdelano** [comment]
From team discussion:

There are some areas where we wrap the low-level HTTP calls w/ retries and we should survey the code so that we don't end up with multiple levels of nested retries.

**Comment by jeremymv2** [comment]
https://github.com/habitat-sh/habitat/pull/7874 establishes a new pattern for HTTP retry attempts, but there is still plenty to do to resolve the entirety of this issue.

For starters:
- [ ] use `retry_builder_api!` throughout the code base on all remaining API calls that are yet not wrapped in retry logic
- [ ] refactor the [pkg upload](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/pkg/upload.rs) logic to use `retry_builder_api` but also take a stab a reducing that commands complexity
- [ ] smart resumption of interrupted downloads (although possibly outside the scope defined here as it entails changes to Builder)
