### ISSUE TITLE
Publish the docs

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#7926]
MVP for the "new" docs

- [ ] Updated Plans doc
- [ ] Updated Studio doc(s)
- [ ] Updated glossary
- [ ] Collate recent content between old & new
- [ ] Crosswalk old & new sites for links & redirects
- [ ] Fix the links
- [ ] Well-formed markdown

**Comment by kagarmoe** [comment]
Done!
